### ISSUE TITLE
Reward calculation for RunEnv

### ISSUE THREAD

**Issue by fgvbrt** [stanfordnmbl/osim-rl#43] opened 2017-07-23 17:58 UTC
Hi, I noticed that  when you calculate reward you don't update last_state to current_state. The only place where last_state is updated is the reset method. 
This means that you don't return one-step reward, but the total reward up to current episode step. 
I think you should fix it :smile:

**Comment by kidzik** [comment] 2017-07-24 00:11
It is updated here https://github.com/stanfordnmbl/osim-rl/blob/master/osim/env/osim.py#L168
I agree it could be cleaner but it is fine (for now).

**Comment by fgvbrt** [comment] 2017-07-24 06:03
Maybe I dont understand something, but:
1) in your link you update last_action, but not last state
2) I noticed that when agent moved forward, it always receive positive reward, even if he is staying on the same place or slightly moving backward.  Here is typical  reward curve over time (lowest value is zero) http://imgur.com/a/be8qF 
3) I explicitly printed `print env.last_state[env.STATE_PELVIS_X], env.current_state[env.STATE_PELVIS_X]` and the first part is always zero, but it should be previous value of the second part

Am i missing something?

**Comment by kidzik** [comment] 2017-07-24 06:37
Unfortunately, that seems right, sorry for this quick incorrect assessment. Since it would quite significantly affect current results and since the current objective function still should lead to 'moving as far as possible', we will try to choose the least harmful solution. Thanks a lot for careful analysis!

**Comment by AdamStelmaszczyk** [comment] 2017-07-24 09:31
Wow, thanks so much fgvbrt for finding this.

I think this issue should be open, until not fixed, so that people can spot it easier. It may be also be a good idea to add a "High priority" label or similar.

> Since it would quite significantly affect current results and since the current objective function still should lead to 'moving as far as possible', we will try to choose the least harmful solution.

I understand that backward compatibility is a factor, however I think it's far more better to just fix it and roll-out next version of osim-rl. Reasons:

1. The challenge says it's "Reinforcement learning environments with musculoskeletal models". The  current implementation is not a reinforcement environment (by the definition in David Silver's course and on Wikipedia), because `compute_reward` doesn't give "immediate reward after transition". I think all of the RL libraries I saw rely on this definition.

2. We still have 60 days of competition left, only first 30 passed. Nobody so far achieved better result on the leaderboard than a baseline submission by admin. So I don't feel the cost of not backward compatible changes is high enough to justify not fixing the env.

**Comment by LiberiFatali** [comment] 2017-07-24 15:51
Since this task is computationally expensive, the agent requires a lot of episodes and timesteps just to learn how to walk. Unless we have enormous processing power in hand, any breaking changes would make our training process restarted from scratch.

This is off topic, however I don't see obstacles in spMohanty (Admin) submission. Is that reaally the baseline?

**Comment by ViktorM** [comment] 2017-07-24 15:58
I would vote for the correct reward formulation, with the recording of last step, 60 days till the end of the challenge is enough time to train and retrain agent.

And join to the question about obstacles.

**Comment by kidzik** [comment] 2017-07-24 16:08
We decided to change the reward and I've prepared a tentative branch https://github.com/stanfordnmbl/osim-rl/tree/iss43 . Since the new and the old measures are correlated we will try to discount the current scores to make them comparable. @LiberiFatali has a good point and we will try to address it fairly, yet for the sake of a more meaningful competition, it seems important to correct the error.

We are testing the new environment now and we will post a new benchmark promptly. Sorry for the mess and thank you for your understanding and discussion!

**Comment by kidzik** [comment] 2017-07-25 18:20
If you tried the iss43 branch, please let us know your experience (here or privately), so that we can roll it out sooner. Note that the difference is that the new reward function is a derivative of the old reward function (modulo a small error on ligaments). So for the models trained previously, taking the cumulative sum of rewards as a reward should yield similar experience, if your algorithm relies on that.

**Comment by fgvbrt** [comment] 2017-07-25 21:23
Hi, I made similar modification by my own and noticed that when I run my previously trained agents I always obtain very high reward related to lig_pen, actually it is higher than reward for moving forward.
Here are typical values of these both reward (first is "movind forward reward " and second is "lig_pen") Maybe you should carefully look at scaling constant for this two parts of reward, I am not sure now that this is possible to learn good policy with this reward:
0.00476280700601 0.0164990073588
0.00413903056655 0.0151963977149
0.00363156499301 0.0128450193735
0.00329636943162 0.0110873209941
0.00307123597201 0.0106107392919
0.00313117791239 0.0111621550313
0.00316452449907 0.0110113162483
0.00302489540878 0.00990658850094
0.00333417318044 0.0087098156985
0.00354273304158 0.00657035539484
0.00423457159953 0.00875325506608
0.00533576647573 0.0165944487833
0.0045510766111 0.0180316189574
0.00353006299279 0.01755132944
0.00277684779291 0.016527103372
0.00245134188634 0.0185393699774
0.00230928468998 0.0208992816518
0.0014924378922 0.0203374645968
0.000731370049012 0.0208180524229
0.000236296382949 0.022882241171

**Comment by kidzik** [comment] 2017-07-25 21:41
Indeed, with the cumulative sum ligament forces were negligible. Now they are not negligible anymore and we also have some issues with returning our benchmark model. I will make them very small in `iss43` branch for testing. Please let us know about any updates -- hopefully we can quickly go back to the normal operation mode of the challenge...

**Comment by syllogismos** [comment] 2017-07-25 22:15
Using the info variable, can you give us a list of different rewards with varying factors. So that we can compare rewards(multiplying factors) at the same time. From this, people can compute from their trained agents, various total_rewards and distances travelled.

How did you come up with 0.0001 earlier? Ideally, we cant make the ligament factor become so insignificant that it plays no role in the training. But what is the ideal scenario, Will it be okay if an agent walks a longer distance, but have a lesser total_reward.

**Comment by kidzik** [comment] 2017-07-25 22:34
I agree that ideally, we want to keep the ligament penalty fairly high (which should lead to more human-like movement), but we also need to reduce the chance of not getting any reasonable results at all, as being in the middle of the challenge. Also, it would be good to keep the setting similar to what is now in the `master` branch, where ligament forces are negligible (yet, they can still matter for similar distances travelled).

`0.0001` came from other experiments in our lab in a different setting. We kept it as-is, since it was ok out-of-the-box (with the cumulative reward).

**Comment by AdamStelmaszczyk** [comment] 2017-07-26 09:32
Just an idea. How about defining the reward as:

```python
# (...) like in compute_reward
delta_x = self.current_state[self.STATE_PELVIS_X] - self.last_state[self.STATE_PELVIS_X]

penalty = math.sqrt(lig_pen) / 1000 # sic, 1000 not 10000

return delta_x - penalty * abs(delta_x)
# equivalent of:
# return delta_x * (1 - penalty) if delta_x >= 0 else delta_x * (1 + penalty)
```
On fgvbrt's data (I only flipped delta_x's sign for lower half to have also negative values) it would look like that:

```
delta_x         √lig_pen / 10000    √lig_pen / 1000     penalty * abs(delta_x)  reward
---------------------------------------------------------------------------------------------
0.004762807     0.0164990074        0.1649900736        0.0007858159            0.0039769911
0.0041390306    0.0151963977        0.1519639771        0.0006289835            0.003510047
0.003631565     0.0128450194        0.1284501937        0.0004664752            0.0031650898
0.0032963694    0.011087321         0.1108732099        0.0003654791            0.0029308904
0.003071236     0.0106107393        0.1061073929        0.0003258808            0.0027453551
0.0031311779    0.011162155         0.1116215503        0.0003495069            0.002781671
0.0031645245    0.0110113162        0.1101131625        0.0003484558            0.0028160687
0.0030248954    0.0099065885        0.099065885         0.0002996639            0.0027252315
0.0033341732    0.0087098157        0.087098157         0.0002904003            0.0030437728
0.003542733     0.0065703554        0.0657035539        0.0002327702            0.0033099629
-0.0042345716   0.0087532551        0.0875325507        0.0003706629            -0.0046052345
-0.0053357665   0.0165944488        0.1659444878        0.000885441             -0.0062212075
-0.0045510766   0.018031619         0.1803161896        0.0008206328            -0.0053717094
-0.003530063    0.0175513294        0.1755132944        0.000619573             -0.004149636
-0.0027768478   0.0165271034        0.1652710337        0.0004589325            -0.0032357803
-0.0024513419   0.01853937          0.1853936998        0.0004544633            -0.0029058052
-0.0023092847   0.0208992817        0.2089928165        0.0004826239            -0.0027919086
-0.0014924379   0.0203374646        0.203374646         0.000303524             -0.0017959619
-0.00073137     0.0208180524        0.2081805242        0.000152257             -0.000883627
-0.0002362964   0.0228822412        0.2288224117        0.000054069             -0.0002903663
```

**Comment by kidzik** [comment] 2017-07-27 17:32
Thanks, @AdamStelmaszczyk! The reward mathematically definitely makes sense and is probably a good approximation of what the old reward was, but we will keep the simpler version, i.e. the current one on the `iss43` branch.
We are working on rolling it out and updating the scores.

**Comment by ctmakro** [comment] 2017-07-29 01:43
off-topic: As I said before, whoever wrote the code should take more sleep...

**Comment by kidzik** [comment] 2017-07-29 01:44
I completely agree.

**Comment by LiberiFatali** [comment] 2017-07-29 01:45
Thanks for the info. Will the timestep be changed to 1000 (it is 500 now) in the grader as well?

**Comment by kidzik** [comment] 2017-07-29 01:46
Yes, it will be 1000 steps.

**Comment by fgvbrt** [comment] 2017-07-29 08:08
Hi, two small details:
1)  Here https://github.com/stanfordnmbl/osim-rl/blob/master/docs/README.md for version 1.4.1 you give link to issue 31, which can be confusing for some people, because actual issue is 43.
2)  This phrase should be corrected, because forces are divided by 10^-7
> The penalty in the total reward is equal to the sum of forces generated by ligaments over the trial, divided by 10000.

**Comment by marioyc** [comment] 2017-07-29 09:26
Also related to the evaluation, would it be possible to increase the number of runs an agent is evaluated on? As mentioned in this [article](https://openreview.net/pdf?id=BJNuErQX-) which discusses on the subject of reproducibility in RL, 5 runs is already a stretch on having a good idea about the average result of an agent, I understand we could do more submissions to get a better estimate, but nothing in the rules gives incentive to the participants to do so, and also displaying the variance of the results of each agent would give us a clearer idea of just how significant is the difference in the results coming from two agents.

In a related topic, since currently the average of all submissions is calculated, this would only give a biased estimate about how the last agent is performing, since normally the participants will continue improving their solutions through the competition, wouldn't it be better to keep something like "average of last K submissions"?

**Comment by AdamStelmaszczyk** [comment] 2017-07-29 14:39
I think Mario made a very good point.

Seems a low hanging fruit to increase the number of runs from 3 to, for example, 10. Adding a column to the leader-board with a variance from runs would also help.

About incentives. The way it works now as far as I know, is that the leader-board keeps your best score, where score is an average return from 3 runs. I think these contestants, who realize that there might be a big variance in scores, have incentive to submit multiple times, to move the score from "the average from runs" to "close to the maximum from the average from runs".

Which is kind of ok, because this is not how the final results are obtained. From README:

> In order to avoid overfitting to the training environment, the top 10 participants will be asked to resubmit their solutions in the second round of the challenge. Environments in the second round will have the same structure but they will be initialized with different seeds. The final ranking will be based on results from the second round.

As I understood, top 10 scores will be obtained by average from 3 runs. This could be problematic. If re-run again (with different seeds) it could give another final top 10 ordering.

One could again increase this 3 to, for example, 50 runs (only for top 10 for final results).

As far as I remember submitting with 3 runs was taking about 6 minutes on my machine, so about 2 minutes per run. So 10 runs should be about 20 minutes, which is fine for submit. And about 100 minutes for final submits from top 10. This assumes that crowdAI.org can handle up to 10 clients communicating with them for about 100 minutes, likely in the same time.

**Comment by kidzik** [comment] 2017-07-29 15:21
@LiberiFatali thanks for pointing out
@marioyc @AdamStelmaszczyk That definitely makes sense, but let's come back to this idea as soon as we fix the main issue from this thread.

**Comment by parilo** [comment] 2017-07-29 16:46
Also it would be nice to test at different seeds at submit in order to avoid overfitting during the challenge. I mean 3 tests for 2 or 3 seeds. So It would be 6 or 9 episodes.

**Comment by kidzik** [comment] 2017-07-29 22:32
The grader computes the right reward now. Rewards of solutions submitted before 13:19 CEST, July 29th will be adjusted.

**Comment by LiberiFatali** [comment] 2017-07-30 09:03
When submitting to new grader, I get this error "502 server error bad gateway". This usually happens at timesteps > 500.

**Comment by AdamStelmaszczyk** [comment] 2017-07-30 10:19
README says the penalty is divided by 10^7 (`10,000,000`) whereas in the current `run.py` on master they are divided by 10^8 (https://github.com/stanfordnmbl/osim-rl/blob/master/osim/env/run.py#L76).

**Comment by marioyc** [comment] 2017-07-30 10:25
@AdamStelmaszczyk it says 10e-8 so it's okay, weird way to write it though

**Comment by fgvbrt** [comment] 2017-07-30 10:26
@AdamStelmaszczyk  1e-8 == 10**-7, you can check in python. {number1}e{number2} in python means number1*10**number2

**Comment by AdamStelmaszczyk** [comment] 2017-07-30 10:36
Oh, right, it says `10e-8`, somehow I "saw" `1e-8`, thanks.

**Comment by kidzik** [comment] 2017-07-30 14:53
@LiberiFatali we got a few `Broken pipe errors` on our side. I've seen that some of your submissions went through. Is it better now? Is there any pattern?
@AdamStelmaszczyk yes, that's correct and super-confusing. We will work out these details later though.

**Comment by LiberiFatali** [comment] 2017-07-31 03:52
It seems ok now. Thank you +1:

**Comment by kidzik** [comment] 2017-07-31 04:20
Thanks, closing the issue for now. We will discuss internally other requests which popped up here. Thank you all for reporting!

**Closed by kidzik** 2017-07-31 04:20 UTC
